"""create product table

Revision ID: 8f26860f201f
Revises: bec5e632abbc
Create Date: 2025-12-12 15:34:02.757891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f26860f201f'
down_revision: Union[str, Sequence[str], None] = 'bec5e632abbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
