"""create edit admins

Revision ID: 91ff80facc52
Revises: c31952c54b1f
Create Date: 2025-12-08 18:46:31.858541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ff80facc52'
down_revision: Union[str, Sequence[str], None] = 'c31952c54b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('admins', 'password_hint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('password_hint', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
