"""create customers table

Revision ID: bec5e632abbc
Revises: ccbc5784194e
Create Date: 2025-12-11 17:56:33.701069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec5e632abbc'
down_revision: Union[str, Sequence[str], None] = 'ccbc5784194e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('birth_day', sa.Date(), nullable=True))
    op.alter_column('customers', 'first_purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_purchase_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('customers', 'birth_day')
    op.drop_column('customers', 'gender')
    # ### end Alembic commands ###
