"""create name of admins

Revision ID: c31952c54b1f
Revises: cf56ee6db84d
Create Date: 2025-12-07 21:43:50.552389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31952c54b1f'
down_revision: Union[str, Sequence[str], None] = 'cf56ee6db84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('admins', sa.Column('last_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'last_name')
    op.drop_column('admins', 'first_name')
    # ### end Alembic commands ###
