"""create new tabels

Revision ID: cf56ee6db84d
Revises: 62e5be313bbf
Create Date: 2025-12-06 18:20:31.376807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf56ee6db84d'
down_revision: Union[str, Sequence[str], None] = '62e5be313bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password_hint',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('admins', 'national_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('admins', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admins', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admins', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admins', 'education',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admins', 'hire_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admins', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('admins', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('admins', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('admins', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('admins_username_key'), 'admins', type_='unique')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('admins_username_key'), 'admins', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('admins', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admins', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admins', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('admins', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('admins', 'hire_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('admins', 'education',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('admins', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('admins', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('admins', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('admins', 'national_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('admins', 'password_hint',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
