"""create add b_list table

Revision ID: cf9ec8e3ccdc
Revises: 4060a4f4fb1c
Create Date: 2025-12-17 17:37:52.190016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9ec8e3ccdc'
down_revision: Union[str, Sequence[str], None] = '4060a4f4fb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'b_list',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'b_list',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
